name: Lint Code Base

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: pull_request

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: docker://github/super-linter:slim-v4@sha256:80ecaa58ad5f9480c66e3c77af5c955831861a41fb78ce7e0ffb1b443eca0f0f
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: false
          VALIDATE_JSCPD: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_YAML: false
